import Head from 'next/head';
import Card from '../components/Card';

const subscriptions = [
  {
    title: 'Netflix',
    tags: ['#netflix', '#movies'],
    price: 34000,
    currency: 'COP',
    time: 'MONTHLY',
    card: {
      type: 'VISA',
      number: 1234,
    },
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css'
        ></link>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <Card />
        <Card />
      </main>
      <style jsx>{`
        .main {
          height: 100%;
          display: grid;
          gap: 20px;
          place-content: center;
        }
      `}</style>
    </>
  );
}
