import Head from 'next/head';
import Card from '../components/Card';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css'
        ></link>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <Card />
      </main>
      <style jsx>{`
        .main {
          height: 100%;
          display: grid;
          place-content: center;
        }
      `}</style>
    </>
  );
}
